tasks:
  # Task: get series torrents
  get_series:
    rss: http://rss.thepiratebay.se/208
    series:
      - Homeland:
          quality: hdtv
      - Castle:
          quality: hdtv
          name_regexp:
            - ^Castle.*\[Cas\]$
      - Game of thrones:
          quality: hdtv
      - Cosmos:
          quality: hdtv
      - Outlander:
          quality: hdtv
    transmission:
      host: localhost
      port: 9091
      username: pi
      password: pi
      removewhendone: no
  
  # Task: init flexget DB with series in STOREX (only run first time)
  seed_series_db:
    # The find plugin will find all of your existing episodes
    find:
      regexp: .*(avi|mkv|mp4)$
      path: /media/STOREX/Series
      recursive: yes
    # We use the manual plugin so that this task only runs when explicitly called
    manual: yes

